name: Format

on:
  push:
    branches:
      - master

jobs:
  swift_format:
    name: swift-format
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Tap
        run: brew tap pointfreeco/formulae
      - name: Install
        run: brew install Formulae/swift-format@5.5
      - name: Format
        run: swift format -i -r --ignore-unparsable-files .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
